export const OPEN_CART = "OPEN_CART"
export const CLOSE_CART = "CLOSE_CART"
export const OPEN_MENU = "OPEN_MENU"
export const CLOSE_MENU = "CLOSE_MENU"
export const OPEN_LOGIN = "OPEN_LOGIN"
export const CLOSE_LOGIN = "CLOSE_LOGIN"
export const CLOSE_SEARCH = "CLOSE_SEARCH"
export const OPEN_SEARCH = "OPEN_SEARCH"